server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/smart_campus_db



spring.security.oauth2.client.registration.google.client-id=549455698297-l5t6ed70l6mva5b56vi5pfk9kurkmgau.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

app.jwtSecret=mySuperStrongSecretKeyThatIsAtLeastSixtyFourCharactersLongForHS512Algorithm1234567890
app.jwtExpirationMs=86400000
app.adminSecret=SUPER_SECRET_ADMIN_KEY_2026

# File upload
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.springframework.security=DEBUG